title: Ganesh Dharmadhikari
logo: /assets/img/DSC0721.jpg
description: MS CS graduate from the University of Utah. Experienced in algebraic & computational aspects number theory. Skilled in Cryptography, algorithms,  science communication & teaching. Deeply nterested in IKS & writing.

# show_downloads: true
theme: jekyll-theme-minimal
