title: Ganesh Dharmadhikari
logo: /assets/img/DSC0721.jpg
description: PhD student at the University of Utah, specializing in mathematical sciences research. Experienced in algebraic and computational aspects of number theory. Proficient in Machine Learning, Data Science, coding, and Mathematics teaching. Skilled in podcast scriptwriting.

# show_downloads: true
theme: jekyll-theme-minimal
