title: Ganesh Dharmadhikari
logo: /assets/img/DSC0721.jpg
description: Currently a PhD student at the School of Computing, University of Utah. Three years of research experience in the domain of mathematical sciences. Also, worked as a research assistant in the area of algebraic and computational aspects of number theory, strengthening my problem-solving and computational skills. Experienced in Machine Learning and Data Science, coding, teaching Mathematics and scriptwriting for podcasts.

# show_downloads: true
theme: jekyll-theme-minimal
