title: Ganesh Dharmadhikari
logo: /assets/img/DSC0721.jpg
description: MS CS graduate from the University of Utah. Experienced in algebraic and computational aspects of number theory. Proficient in Cryptography, algorithms,  science communication and Mathematics teaching. Interested in IKS and creative writing.

# show_downloads: true
theme: jekyll-theme-minimal
